### ISSUE TITLE
TSD error

### ISSUE THREAD

**Issue by microshine** [brianloveswords/base64url#10]
I'm using your lib from npm. But when I start to compile my oun module a have TS error with duplicated node.d.ts declarations. You add folder `typings` to npm lib. I think it would be better to distribute base64url via TSD. I created base64url.d.ts and made [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10614#issuecomment-239649113).

**Comment by microshine** [comment]
`base64url` is in TSD now [base64url.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/base64url)

```
sudo npm install typings -g
typings search base64url
typings install dt~base64url --global --save
```

I think it's the best practis of using tsd

**Comment by r-ising** [comment]
+1 

i have the same problem..

**Comment by pnizer** [comment]
I got the following error message: "Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition."

**Comment by MylesBorins** [comment]
This project has been relying on "types/node" since 3.0.0 which I think should hopefully solve this issue.
