### ISSUE TITLE
README needs brackets for encode example

### ISSUE THREAD

**Issue by goatandsheep** [brianloveswords/base64url#12]
In the README, please change the following (lines 31, 33):

```
 ### base64url(input: string | Buffer, encoding: string = "utf8"): string
 ### base64url.encode(input: string | Buffer, encoding: string = "utf8"): string
```

to:

```
### base64url(input: string | Buffer, {encoding: "utf8"}): string
### base64url.encode(input: string | Buffer, {encoding: "utf8"}): string
```

**Comment by MylesBorins** [comment]
We're a bit confused by this... it would appear the docs are already correct, can you expand?

**Comment by goatandsheep** [comment]
Hi @MylesBorins I wrote this ticket >2 years ago, so I don't quite remember why, but I think at the time the only thing that was working for me was using an object with the encoding type inside. looks like I was either using it wrong or you've updated the package
