### ISSUE TITLE
Can we please not put typescript definitions to the final package

### ISSUE THREAD

**Issue by RachelSatoyama** [brianloveswords/base64url#13]
By default typescript tries to resolve declaration by searching, among other locations, in node_modules project - that leads to duplicate definition error which is not that trivial to get rid off (at least some not that well documented steps should be taken).

Here's a link to give you an idea - https://github.com/Microsoft/TypeScript/issues/6964

It would be very nice if typescript definitions won't be included to the final package.
After all not a big deal but those a just redundant files that a increasing package size for no reason.

**Comment by ssougnez** [comment]
Hi,

especially when "@types/base64url" exists (for TS 2). 

I ended up not using this package because of all the duplicates error I got.

Regards

**Comment by jorrit-wehelp** [comment]
Yes, this can cause duplicate definitions because of the included node typings.

Would be even better to just drop typings, since it's not needed anymore with TypeScript 2.0

I see somebody already did it, but there's no pull request for it yet...?
https://github.com/microshine/base64url

**Comment by philkunz** [comment]
This package is coded in TypeScript and typings are already linked in package.json. So just remove the typings directory and define @types/node  as peer dependency. No need for any other external @types scoped modules.

**Comment by heycalmdown** [comment]
I made [npm://base64url-adhoc](https://www.npmjs.com/package/base64url-adhoc) for temporary use before #18 accepted. You can't replace this with the original library inside existing module like `jsonwebtoken`. Just use it for typing if you use `base64url` directly in your code.

**Comment by AndyBarron** [comment]
I'm getting bitten by this too -- the duplicate definitions error :/

**Comment by kumar-muthu** [comment]
I ended up writing an ugly build script using gulp, to delete all .ts files from the nodemodules\base64url folder before compiling my typescript project. This works for me.

**Comment by philkunz** [comment]
I was subscribed to this subject for some reason.
Just use js-base64, it is a way better lib.

**Comment by philkunz** [comment]
@rageycomma Then you can't see very far.

**Comment by MylesBorins** [comment]
Closing as resolved
