### ISSUE TITLE
Do not publish global typings to npm

### ISSUE THREAD

**Issue by demurgos** [brianloveswords/base64url#20]
Hi,
Your package publishes global typings to npm. This causes conflicts with other (and more recent / acurate) definitions for Node. This module is simply unusable with full TS checks.

Since you use `typings`, you shouldn't even publish your typings directory but let `typings` resolve the dependencies with your `typings.json` file. `typings` is now deprecated in favor of `@types`, I'd recommend to switch to `@types` while fixing this issue.

**Comment by dauledk** [comment]
Hi @demurgos  - how do you solve this in your project?

**Comment by demurgos** [comment]
@dauledk 
I don't have time to deal with these sorts of issues and even if your solution could work in a postinstall hook, it remains a hack.
This issue is so bad that I just switched to another lib: [`base64-url`](https://www.npmjs.com/package/base64-url) (with a dash).

@brianloveswords Since I switched to another lib, I did not follow this issue actively, but it seems that multiple other people upvoted this issue. I appreciate that you tried to provide type definitions, but it's been 4 months that **your library is unusable with Typescript**. Please consider one of the solutions I mentioned in the first post.

**Comment by MylesBorins** [comment]
We believe that this was fixed in 3.0.0. Please let us know if that is incorrect and we'll re-open the PR
