### ISSUE TITLE
Vunerability "npm audit"

### ISSUE THREAD

**Issue by ktquez** [brianloveswords/base64url#30]
I'm trying to install gh-pages and received from npm audit the message:
=== npm audit security report ===
Moderate: Out-of-bounds Read
Package: base64url
Patched in: >=3.0.0
Dependency of: gh-pages [dev]
Path: gh-pages > base64url
More info: https://nodesecurity.io/advisories/658

[!] 1 vulnerability found - Packages audited: 47 (47 dev, 0 optional)
Severity: 1 Moderate

**Comment by soufian044** [comment]
+1

**Comment by jeffwilcox** [comment]
The message is accurate in that the vulnerability is only an issue when used in Node.js versions up to and including Node 4. These days (LTS schedule: https://github.com/nodejs/Release) Node 4 is not even support any longer.

I wonder if it would help to do something such as update `package.json` to add an engines clause, with the hope that after publishing a minor increment to 3.0.1, the CVE associated with the package would no longer apply with such an engine check...

i.e. adding `{ "engines" : { "node" : ">= 6.0.0" } }` to package.json, or if need really be, adding some kind of explicit check in the library?

**Comment by MylesBorins** [comment]
This has been fixed in master, soon to be fixed in 4.0.0
