### ISSUE TITLE
Node 4 throws "Unexpected token" error in `encode`

### ISSUE THREAD

**Issue by dskrvk** [brianloveswords/base64url#31]
> /home/dskrvk/workspace/wise/wise-api/node_modules/base64url/dist/base64url.js:4
> function encode(input, encoding = "utf8") {
> ------------------------------------------^

Same in Travis: https://travis-ci.org/brianloveswords/base64url/jobs/379778757

**Comment by MylesBorins** [comment]
As of 4.0.0 we have dropped support for Node.js 4.x

Node.js no longer supporting 4.x, it is likely a good idea to upgrade your projects.
