### ISSUE TITLE
ES6 target should be replaced by ES5

### ISSUE THREAD

**Issue by behandelcoach** [brianloveswords/base64url#37]
ES5 compatible modules, such as 'node-jose', use this module as one of their dependencies. Because the module has been compiled to ES6 it causes problems in browsers that are not ES6 compatible. In our use case the iOS 9 browser.

Can you change 'es6' to 'es5' in the 'tsconfig.json' in order to resolve these type of issues?

**Comment by MylesBorins** [comment]
Fixed by https://github.com/brianloveswords/base64url/pull/40
