### ISSUE TITLE
Where can I get the javascript source code without npm?

### ISSUE THREAD

**Issue by bronze1man** [brianloveswords/base64url#45]
After download serval `npm install` fail project. I do not want to touch npm anymore... Source code in the git project should be the `forever` solution for me.
For example: https://github.com/keithnorm/simple-webrtc-video-chat/issues/6

I just want to copy and paste source code into my project. But I can not find javascript source code.
Please provide one in the git project or in github download.

**Comment by MylesBorins** [comment]
https://github.com/brianloveswords/base64url/archive/v3.0.1.tar.gz
https://github.com/brianloveswords/base64url/releases

**Comment by bronze1man** [comment]
@MylesBorins 
Thanks.

The typescript source code just call another api called Buffer.from , which is not what I want.

I have already find the js source code of base64 encode. https://github.com/google/closure-library/blob/master/closure/goog/crypt/base64.js#L124

By the way, the file you give do not have javascript source code, only typescript source code.
