### ISSUE TITLE
ES6 const

### ISSUE THREAD

**Issue by simplesmiler** [brianloveswords/base64url#5]
Hello. I've looked through the npm packages that implement base64 url encoding, and your one seems to be the best fit. But I've got a small issue with it.

Using es6 features (such as `const`) in code published to npm currently breaks environments that do not support these features, including IE10 and older (using browserify). This issue currently stops me from using this package in the app.

Would you mind if I make a PR replacing `const`s with `var`s?

**Comment by tunnckoCore** [comment]
:+1: 

@simplesmiler try this one https://github.com/joaquimserafim/base64-url/, looks better to me.

**Comment by brianloveswords** [comment]
I would totally accept a pr that replaces `const` with `var`.

**Comment by brianloveswords** [comment]
Closed by #6

**Comment by simplesmiler** [comment]
:+1:
