### ISSUE TITLE
Internal base64 decoder doesn't flag incorrect data

### ISSUE THREAD

**Issue by cyberphone** [brianloveswords/base64url#7]
I added this to a local version of test:

``` javascript
test('from base64url to string', function (t) {
  const b64url = 'a';
  const result = base64url.encode(base64url.decode(b64url,'binary'));
  t.same(result, b64url, 'should NOT be able to decode, it should throw an error');
  t.end();
});
```

I also think there are issues with line-breaks which is outside of Base64URL

**Comment by MylesBorins** [comment]
The Node.js Buffer object doesn't currently throw

```
> Buffer.from('a', 'base64');
<Buffer >
```

I don't think throwing on here is the appropriate behavior. 

I'm going to go ahead and close this issue, thanks for reporting. If you think I missed something chime in and we can discuss.
