### ISSUE TITLE
Massive number of Dependencies via Meow

### ISSUE THREAD

**Issue by MarkHerhold** [brianloveswords/base64url#9]
Hi, I was looking through the dependency tree of my dependencies and drilled down to this module via `jwa`/`jws`. This module relies on meow v2 which has a lot of dependencies, but not as many as v3. 

Here's the current dependency tree this module, whose only job is to encode and decode strings: http://npm.anvaka.com/#/view/2d/base64url

Going forward I think it would be ideal if this module dropped CLI support. To me a CLI is a separate concern and should be a separate module, e.g. `base64url-cli`

Thoughts?

**Comment by brianloveswords** [comment]
Yeah, I agree. Just published `v2.0.0` which now has no external dependencies. I'll work on updating `jwa` and `jws` soon.

**Comment by MarkHerhold** [comment]
@brianloveswords Awesome! Thanks Brian!
